# Generated by Django 4.2.9 on 2026-05-08 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dsa', 'DSA Problems'), ('course', 'Course / Lectures'), ('project', 'Project Work'), ('revision', 'Revision'), ('mock', 'Mock Interview'), ('other', 'Other')], default='other', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('once', 'One Time')], default='daily', max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1, help_text="e.g. 2 for '2 DSA problems'")),
                ('is_default', models.BooleanField(default=False, help_text='Auto-assigned to all group members')),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, help_text='For one-time tasks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, help_text='How many units completed (e.g. 2 problems)')),
                ('note', models.TextField(blank=True, help_text='Optional note like LeetCode problem links')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
